name: datalab

on:
  push:
    branches: [ datalab ]
  pull_request:
    branches: [ datalab ]

jobs:
  grade_job:
    runs-on: ubuntu-latest
    name: datalab
    steps:
    - name: Grading
      id: grade
      uses: pamoreno/datalab-action@v2
      with:
        target: 'grade'
    # Use the output from the `hello` step
    - name: Get the output log
      run: echo "The result was ${{ steps.grade.outputs.result }}"
